spring:
  datasource:
    url: jdbc:postgresql://cockroachdb:26257/snap_park?sslmode=disable
    username: root
    password: snap_park
  jpa:
    database-platform: org.hibernate.dialect.CockroachDBDialect
    hibernate:
      ddl-auto: update

server:
  port: 9090
