########################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################

spring:
  output:
    ansi:
      enabled: ALWAYS

#  liquibase:
#    change-log: classpath:db/changelog-master.xml
#    default-schema:
#    drop-first: false
#    contexts: crdb
#    enabled: true


  datasource:
    url: jdbc:postgresql://127.0.0.1:26257/defaultdb?sslmode=disable&user=root
    driver-class-name: org.postgresql.Driver
    username: root
    password: snappark

  jpa:
    open-in-view: false
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.CockroachDB201Dialect
        #dialect: org.hibernate.dialect.PostgreSQL95Dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

server:
  port: 9090