TRAFFIC = [
    {
        "type"      :   "TRF",
        "ts"        :   12029323,
        "park"      :   1,
        "sensor"    :   0,
        "entering"  :   True,
        "vehicle"   :   1,
        "veh_type"  :   'A',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029330,
        "park"      :   1,
        "sensor"    :   0,
        "entering"  :   False,
        "vehicle"   :   2,
        "veh_type"  :   'B',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029340,
        "park"      :   2,
        "sensor"    :   1,
        "entering"  :   True,
        "vehicle"   :   3,
        "veh_type"  :   'A',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029350,
        "park"      :   2,
        "sensor"    :   1,
        "entering"  :   False,
        "vehicle"   :   4,
        "veh_type"  :   'C',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029360,
        "park"      :   3,
        "sensor"    :   2,
        "entering"  :   True,
        "vehicle"   :   5,
        "veh_type"  :   'B',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029370,
        "park"      :   3,
        "sensor"    :   2,
        "entering"  :   False,
        "vehicle"   :   6,
        "veh_type"  :   'A',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029380,
        "park"      :   4,
        "sensor"    :   3,
        "entering"  :   True,
        "vehicle"   :   7,
        "veh_type"  :   'C',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029390,
        "park"      :   4,
        "sensor"    :   3,
        "entering"  :   False,
        "vehicle"   :   8,
        "veh_type"  :   'A',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029400,
        "park"      :   5,
        "sensor"    :   4,
        "entering"  :   True,
        "vehicle"   :   9,
        "veh_type"  :   'B',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029410,
        "park"      :   5,
        "sensor"    :   4,
        "entering"  :   False,
        "vehicle"   :   10,
        "veh_type"  :   'C',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029420,
        "park"      :   6,
        "sensor"    :   5,
        "entering"  :   True,
        "vehicle"   :   11,
        "veh_type"  :   'A',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029430,
        "park"      :   6,
        "sensor"    :   5,
        "entering"  :   False,
        "vehicle"   :   12,
        "veh_type"  :   'B',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029440,
        "park"      :   7,
        "sensor"    :   6,
        "entering"  :   True,
        "vehicle"   :   13,
        "veh_type"  :   'C',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029450,
        "park"      :   7,
        "sensor"    :   6,
        "entering"  :   False,
        "vehicle"   :   14,
        "veh_type"  :   'A',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029460,
        "park"      :   8,
        "sensor"    :   7,
        "entering"  :   True,
        "vehicle"   :   15,
        "veh_type"  :   'B',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029470,
        "park"      :   8,
        "sensor"    :   7,
        "entering"  :   False,
        "vehicle"   :   16,
        "veh_type"  :   'C',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029480,
        "park"      :   9,
        "sensor"    :   8,
        "entering"  :   True,
        "vehicle"   :   17,
        "veh_type"  :   'A',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029490,
        "park"      :   9,
        "sensor"    :   8,
        "entering"  :   True,
        "vehicle"   :   18,
        "veh_type"  :   'B',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029500,
        "park"      :   10,
        "sensor"    :   9,
        "entering"  :   False,
        "vehicle"   :   19,
        "veh_type"  :   'C',
    },
    {
        "type"      :   "TRF",
        "ts"        :   12029510,
        "park"      :   10,
        "sensor"    :   9,
        "entering"  :   False,
        "vehicle"   :   20,
        "veh_type"  :   'A',
    },
]


LIGHT_LEVELS = [
    {
        "type"      :   "LGT",
        "ts"        :   120293230,
        "park"      :   1,
        "sensor"    :   0,
        "intensity" :   107527.25,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293240,
        "park"      :   1,
        "sensor"    :   0,
        "intensity" :   99033.75,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293250,
        "park"      :   2,
        "sensor"    :   1,
        "intensity" :   124679.5,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293260,
        "park"      :   2,
        "sensor"    :   1,
        "intensity" :   88011.0,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293270,
        "park"      :   3,
        "sensor"    :   2,
        "intensity" :   135882.75,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293280,
        "park"      :   3,
        "sensor"    :   2,
        "intensity" :   100405.25,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293290,
        "park"      :   4,
        "sensor"    :   3,
        "intensity" :   116794.0,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293300,
        "park"      :   4,
        "sensor"    :   3,
        "intensity" :   89001.5,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293310,
        "park"      :   5,
        "sensor"    :   4,
        "intensity" :   143209.25,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293320,
        "park"      :   5,
        "sensor"    :   4,
        "intensity" :   97563.75,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293330,
        "park"      :   6,
        "sensor"    :   5,
        "intensity" :   122718.5,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293340,
        "park"      :   6,
        "sensor"    :   5,
        "intensity" :   83487.0,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293350,
        "park"      :   7,
        "sensor"    :   6,
        "intensity" :   105642.75,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293360,
        "park"      :   7,
        "sensor"    :   6,
        "intensity" :   91116.25,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293370,
        "park"      :   8,
        "sensor"    :   7,
        "intensity" :   98028.0,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293380,
        "park"      :   8,
        "sensor"    :   7,
        "intensity" :   107527.25,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293390,
        "park"      :   9,
        "sensor"    :   8,
        "intensity" :   116026.5,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293400,
        "park"      :   9,
        "sensor"    :   8,
        "intensity" :   94440.0,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293410,
        "park"      :   10,
        "sensor"    :   9,
        "intensity" :   125275.5,
    },
    {
        "type"      :   "LGT",
        "ts"        :   120293420,
        "park"      :   10,
        "sensor"    :   9,
        "intensity" :   87358.5,
    },
]


TEMPERATURE_LEVELS = [
    {
        "type"          :   "TMP",
        "ts"            :   1202932093,
        "park"          :   1,
        "sensor"        :   5,
        "temperature"   :   21.0173,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932100,
        "park"          :   1,
        "sensor"        :   5,
        "temperature"   :   22.5489,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932110,
        "park"          :   2,
        "sensor"        :   6,
        "temperature"   :   20.4856,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932120,
        "park"          :   2,
        "sensor"        :   6,
        "temperature"   :   23.9787,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932130,
        "park"          :   3,
        "sensor"        :   7,
        "temperature"   :   19.7532,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932140,
        "park"          :   3,
        "sensor"        :   7,
        "temperature"   :   24.5126,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932150,
        "park"          :   4,
        "sensor"        :   8,
        "temperature"   :   18.9907,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932160,
        "park"          :   4,
        "sensor"        :   8,
        "temperature"   :   25.0463,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932170,
        "park"          :   5,
        "sensor"        :   9,
        "temperature"   :   18.2341,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932180,
        "park"          :   5,
        "sensor"        :   9,
        "temperature"   :   25.7849,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932190,
        "park"          :   6,
        "sensor"        :   10,
        "temperature"   :   17.5178,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932200,
        "park"          :   6,
        "sensor"        :   10,
        "temperature"   :   26.5235,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932210,
        "park"          :   7,
        "sensor"        :   11,
        "temperature"   :   16.8384,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932220,
        "park"          :   7,
        "sensor"        :   11,
        "temperature"   :   27.2621,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932230,
        "park"          :   8,
        "sensor"        :   12,
        "temperature"   :   16.1941,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932240,
        "park"          :   8,
        "sensor"        :   12,
        "temperature"   :   28.0007,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932250,
        "park"          :   9,
        "sensor"        :   13,
        "temperature"   :   15.5824,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932260,
        "park"          :   9,
        "sensor"        :   13,
        "temperature"   :   28.7393,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932270,
        "park"          :   10,
        "sensor"        :   14,
        "temperature"   :   15.0017,
    },
    {
        "type"          :   "TMP",
        "ts"            :   1202932280,
        "park"          :   10,
        "sensor"        :   14,
        "temperature"   :   29.4779,
    },
]


AQ_LEVELS = [
    {
        "type"      :   "AQ",
        "ts"        :   1202932093,
        "park"      :   1,
        "sensor"    :   6,
        "aqi"       :   21.0173,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932100,
        "park"      :   1,
        "sensor"    :   6,
        "aqi"       :   22.5489,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932110,
        "park"      :   2,
        "sensor"    :   7,
        "aqi"       :   20.4856,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932120,
        "park"      :   2,
        "sensor"    :   7,
        "aqi"       :   23.9787,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932130,
        "park"      :   3,
        "sensor"    :   8,
        "aqi"       :   19.7532,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932140,
        "park"      :   3,
        "sensor"    :   8,
        "aqi"       :   24.5126,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932150,
        "park"      :   4,
        "sensor"    :   9,
        "aqi"       :   18.9907,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932160,
        "park"      :   4,
        "sensor"    :   9,
        "aqi"       :   25.0463,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932170,
        "park"      :   5,
        "sensor"    :   10,
        "aqi"       :   18.2341,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932180,
        "park"      :   5,
        "sensor"    :   10,
        "aqi"       :   25.7849,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932190,
        "park"      :   6,
        "sensor"    :   11,
        "aqi"       :   17.5178,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932200,
        "park"      :   6,
        "sensor"    :   11,
        "aqi"       :   26.5235,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932210,
        "park"      :   7,
        "sensor"    :   12,
        "aqi"       :   16.8384,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932220,
        "park"      :   7,
        "sensor"    :   12,
        "aqi"       :   27.2621,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932230,
        "park"      :   8,
        "sensor"    :   13,
        "aqi"       :   16.1941,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932240,
        "park"      :   8,
        "sensor"    :   13,
        "aqi"       :   28.0007,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932250,
        "park"      :   9,
        "sensor"    :   14,
        "aqi"       :   15.5824,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932260,
        "park"      :   9,
        "sensor"    :   14,
        "aqi"       :   28.7393,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932270,
        "park"      :   10,
        "sensor"    :   15,
        "aqi"       :   15.0017,
    },
    {
        "type"      :   "AQ",
        "ts"        :   1202932280,
        "park"      :   10,
        "sensor"    :   15,
        "aqi"       :   29.4779,
    },
]




